openapi: 3.0.0
servers:
  - description: Workshop API Dev
    url: https://dev-4.gcp-workshop-chtcz5.awsrnd.link/mfes/one/api
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/csvsf/frontend-one-api/0.0.1
info:
  description: Istio Routing Workshop BFF API
  version: "0.0.1"
  title: Istio Routing Workshop BFF API
tags:
  - name: svc-one-backend-one
    description: svc-one microservice from backend-one namespace
  - name: svc-two-backend-one
    description: svc-two microservice from backend-one namespace
  - name: svc-exernal
    description: external US Patent service https://developer.uspto.gov/ds-api
paths:
  /anything/services/one:
    get:
      tags:
        - svc-one-backend-one
      summary: calls svc-one microservice
      operationId: callSvcOneBackendOne
      responses:
        '200':
          description: positive response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /something-else/two:
    get:
      tags:
        - svc-two-backend-one
      summary: calls svc-two microservice
      operationId: callSvcTwoBackendOne
      responses:
        '200':
          description: positive response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /uspto/ds-api:
    get:
      tags:
        - svc-external
      summary: calls external microservice
      operationId: callSvcExternal
      responses:
        '200':
          description: Returns a list of data sets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/USPTOResponse'
              example:
                {
                  "total": 2,
                  "apis": [
                    {
                      "apiKey": "oa_citations",
                      "apiVersionNumber": "v1",
                      "apiUrl": "https://developer.uspto.gov/ds-api/oa_citations/v1/fields",
                      "apiDocumentationUrl": "https://developer.uspto.gov/ds-api-docs/index.html?url=https://developer.uspto.gov/ds-api/swagger/docs/oa_citations.json"
                    },
                    {
                      "apiKey": "cancer_moonshot",
                      "apiVersionNumber": "v1",
                      "apiUrl": "https://developer.uspto.gov/ds-api/cancer_moonshot/v1/fields",
                      "apiDocumentationUrl": "https://developer.uspto.gov/ds-api-docs/index.html?url=https://developer.uspto.gov/ds-api/swagger/docs/cancer_moonshot.json"
                    }
                  ]
                }
components:
  schemas:
    MessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    USPTOResponse:
      type: object
      properties:
        total:
          type: integer
        apis:
          type: array
          items:
            type: object
            properties:
              apiKey:
                type: string
                description: To be used as a dataset parameter value
              apiVersionNumber:
                type: string
                description: To be used as a version parameter value
              apiUrl:
                type: string
                format: uriref
                description: "The URL describing the dataset's fields"
              apiDocumentationUrl:
                type: string
                format: uriref
                description: A URL to the API console for each API
